name: ktlint-check

on:
push:
  branches:
    - develop
    - release
    - main

pull_request:
  branches:
    - develop
    - release
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
          cache: gradle

      - name: add google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > ./app/google-services.json

      - name: Build with Gradle
        run: ./gradlew build

      - name: Lint Code Style
        run: ./gradlew ktlintCheck
